POST http://localhost:3000/task
Content-Type: application/json

{
    "name": "Ride your bike",
    "desc": "The Task Three",
    "status": false
}

###

GET http://localhost:3000/task/list

###
GET http://localhost:3000/task/list/5f33a3d892133401423fc22e

###
DELETE http://localhost:3000/task/delete-all

###
PATCH http://localhost:3000/task/edit/5f33a3d892133401423fc22e
Content-Type: application/json

{
    "name":"updated new task"
}

###

DELETE http://localhost:3000/task/list/5f32a363fb47a8012a573298